const D=window.BCP_DATA; let view='today'; let date=new Date(); let deferredPrompt=null; const $=s=>document.querySelector(s); const esc=s=>(s||'—').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
function iso(d){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}; function key(d){return String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')};
function lesson(morning){let k=key(date), fixed=(morning?D.fixedMorning:D.fixedEvening)[k]; if(fixed)return {...fixed,feast:D.feasts[k]}; let tab=(morning?D.mattins:D.evensong)[String(date.getMonth()+1)]||[]; return {...(tab[date.getDate()-1]||{first:'—',second:'—'}),feast:D.feasts[k]};}
function ps(){return D.psalms[Math.min(date.getDate(),30)-1]||{morning:'—',evening:'—'}};
function easter(y){let a=y%19,b=Math.floor(y/100),c=y%100,d=Math.floor(b/4),e=b%4,f=Math.floor((b+8)/25),g=Math.floor((b-f+1)/3),h=(19*a+b-d-g+15)%30,i=Math.floor(c/4),k=c%4,l=(32+2*e+2*i-h-k)%7,m=Math.floor((a+11*h+22*l)/451),mo=Math.floor((h+l-7*m+114)/31),day=((h+l-7*m+114)%31)+1;return new Date(y,mo-1,day)}
function add(d,n){let x=new Date(d);x.setDate(x.getDate()+n);return x} function same(a,b){return iso(a)===iso(b)}
function season(){let k0=key(date), feast=D.feasts[k0]; if(feast)return feast; let e=easter(date.getFullYear()); let special=[[0,'Easter Day'],[-2,'Good Friday'],[-7,'Palm Sunday'],[-46,'Ash Wednesday'],[39,'Ascension Day'],[49,'Whitsunday'],[56,'Trinity Sunday']]; for(let [n,t] of special)if(same(date,add(e,n)))return t; let nov30=new Date(date.getFullYear(),10,30), adv=new Date(nov30); adv.setDate(nov30.getDate()-nov30.getDay()); if(date>=adv&&date<new Date(date.getFullYear(),11,25))return 'Advent'; if(date>=new Date(date.getFullYear(),11,25)||date<new Date(date.getFullYear(),0,6))return 'Christmastide'; if(date<e&&date>add(e,-46))return 'Lent'; if(date>e&&date<add(e,49))return 'Eastertide'; return 'Ordinary Day in the Church Year'}
function top(){return `<div class="datebar"><input id="date" type="date" value="${iso(date)}"><button class="secondary" onclick="date=new Date();render()">Today</button></div><h1>${date.toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric',year:'numeric'})}</h1><div class="subtitle">${esc(season())}</div>`}
function card(title,p,l,v){return `<div class="card"><h2>${title}</h2>${l.feast?`<b>${esc(l.feast)}</b>`:''}<p>Psalms: ${esc(p)}<br>First Lesson: ${esc(l.first)}<br>Second Lesson: ${esc(l.second)}</p><button class="primary" onclick="view='${v}';render()">Pray the Office</button></div>`}
function today(){let p=ps(),m=lesson(true),e=lesson(false);return top()+`<div class="cardgrid">${card('Morning Prayer (Mattins)',p.morning,m,'morning')}${card('Evening Prayer (Evensong)',p.evening,e,'evening')}</div><div class="settings"><button class="secondary" onclick="changeFont(-1)">A−</button><button class="secondary" onclick="changeFont(1)">A+</button><button class="secondary" onclick="view='litany';render()">The Litany</button></div><div class="notice">This web edition works as an installable PWA. Once hosted over HTTPS, use your browser’s “Add to Home screen” command; after the first visit the app shell and lectionary remain available offline.</div>`}
const O=D.office; function sec(t,b,r=false){return `<section class="section"><h2>${esc(t)}</h2>${r?'<div class="rubric">According to the 1662 Book of Common Prayer</div>':''}<p>${esc(b||'')}</p></section>`}
function office(morning){let l=lesson(morning),p=ps(),ap=morning?p.morning:p.evening; let parts=[sec(morning?'The Order for Morning Prayer':'The Order for Evening Prayer',date.toLocaleDateString(),true),sec('Opening Sentences',morning?'At Morning Prayer, the Minister shall read with a loud voice some one or more of these sentences of the Scriptures.':'At Evening Prayer, the Minister shall read with a loud voice some one or more of these sentences of the Scriptures.'),sec('Exhortation',O.EXHORTATION),sec('General Confession',O.CONFESSION),sec('Absolution',O.ABSOLUTION),sec('The Lord’s Prayer',O.LORDS_PRAYER),sec('Preces',O.PRECES)]; if(morning)parts.push(sec('Venite, exultemus Domino — Psalm 95',O.VENITE)); parts.push(sec('The Psalms appointed — '+ap,'Use the Coverdale Psalter for Psalms '+ap+'.')); parts.push(sec('The First Lesson — '+l.first,'The appointed lesson is '+l.first+'.')); parts.push(sec(morning?'Te Deum laudamus':'Magnificat',morning?O.TE_DEUM:O.MAGNIFICAT)); parts.push(sec('The Second Lesson — '+l.second,'The appointed lesson is '+l.second+'.')); parts.push(sec(morning?'Benedictus':'Nunc dimittis',morning?O.BENEDICTUS:O.NUNC_DIMITTIS)); parts.push(sec('The Apostles’ Creed',O.CREED),sec('Suffrages',O.SUFFRAGES),sec('The Collect for Peace',morning?O.MORNING_PEACE:O.EVENING_PEACE),sec(morning?'The Collect for Grace':'The Collect for Aid against all Perils',morning?O.MORNING_GRACE:O.EVENING_PERILS),sec('A Prayer for the King’s Majesty',O.PRAYER_FOR_KING),sec('A Prayer for the Royal Family',O.PRAYER_FOR_ROYAL_FAMILY),sec('A Prayer for the Clergy and People',O.PRAYER_FOR_CLERGY),sec('A Prayer of St. Chrysostom',O.CHRYSOSTOM),sec('The Grace',O.GRACE)); return top()+parts.join('')}
function render(){let app=$('#app');app.innerHTML=view==='today'?today():view==='morning'?office(true):view==='evening'?office(false):top()+sec('The Litany',D.litany,true); let inp=$('#date');if(inp)inp.onchange=e=>{let [y,m,d]=e.target.value.split('-').map(Number);date=new Date(y,m-1,d);render()}; document.documentElement.style.setProperty('--font',(localStorage.fontSize||18)+'px');window.scrollTo(0,0)}
function changeFont(n){localStorage.fontSize=Math.max(15,Math.min(25,+(localStorage.fontSize||18)+n));render()} document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{view=b.dataset.view;render()}); $('#theme').onclick=()=>{document.body.classList.toggle('dark');localStorage.dark=document.body.classList.contains('dark')?'1':'0'}; if(localStorage.dark==='1')document.body.classList.add('dark'); window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#install').hidden=false}); $('#install').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('#install').hidden=true}}; if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js'); render();